<?xml version="1.0"?>
<robot name="my_quadracopter" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Materiales -->
  <material name="gray"><color rgba="0.5 0.5 0.5 1.0"/></material>
  <material name="black"><color rgba="0.0 0.0 0.0 1.0"/></material>
  <material name="blue"><color rgba="0.0 0.0 1.0 1.0"/></material>

  <!-- Cuerpo central -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.2 0.2 0.05"/></geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.2 0.2 0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Macro de brazo con motor -->
  <xacro:macro name="arm_with_motor" params="name parent yaw arm_length">
    <xacro:property name="ox" value="${0.5 * arm_length * cos(yaw)}"/>
    <xacro:property name="oy" value="${0.5 * arm_length * sin(yaw)}"/>
    <xacro:property name="mx" value="${arm_length * cos(yaw)}"/>
    <xacro:property name="my" value="${arm_length * sin(yaw)}"/>

    <link name="${name}_arm">
      <visual>
        <origin xyz="${ox} ${oy} 0" rpy="${pi/2} 0 ${-1 * yaw}"/>
        <geometry><cylinder length="${arm_length}" radius="0.01"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="${ox} ${oy} 0" rpy="${pi/2} 0 ${-1 * yaw}"/>
        <geometry><cylinder length="${arm_length}" radius="0.01"/></geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="joint_${name}_arm" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_arm"/>
      <origin xyz="${ox} ${oy} 0" rpy="0 0 0"/>
    </joint>

    <link name="${name}_motor">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.02" radius="0.02"/></geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.02" radius="0.02"/></geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="joint_${name}_motor" type="continuous">
      <parent link="${name}_arm"/>
      <child link="${name}_motor"/>
      <origin xyz="${mx} ${my} 0.02" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="1.5"/>
    </joint>
  </xacro:macro>

  <!-- Cuatro brazos con motores -->
  <xacro:arm_with_motor name="front_left"  parent="base_link" yaw="0.7854"  arm_length="0.2"/>
  <xacro:arm_with_motor name="front_right" parent="base_link" yaw="-0.7854" arm_length="0.2"/>
  <xacro:arm_with_motor name="back_left"   parent="base_link" yaw="2.3562"  arm_length="0.2"/>
  <xacro:arm_with_motor name="back_right"  parent="base_link" yaw="-2.3562" arm_length="0.2"/>

  <gazebo>
    <!-- Plugin de esfuerzos propio (sin <ros>): t贸picos ABSOLUTOS usando __NS__ -->
    <plugin name="wrenches_plugin" filename="libwrenches_plugin.so">
      <link_name_motor1>front_left_motor</link_name_motor1>
      <topic_motor1>__NS__/fl_motor</topic_motor1>

      <link_name_motor2>front_right_motor</link_name_motor2>
      <topic_motor2>__NS__/fr_motor</topic_motor2>

      <link_name_motor3>back_left_motor</link_name_motor3>
      <topic_motor3>__NS__/bl_motor</topic_motor3>

      <link_name_motor4>back_right_motor</link_name_motor4>
      <topic_motor4>__NS__/br_motor</topic_motor4>
    </plugin>

    <!-- IMU: <ros><namespace> con __NS__ y t贸picos RELATIVOS -->
    <plugin name="imu_plugin" filename="libimu_plugin.so">
      <link_name_imu>base_link</link_name_imu>
      <frame_id_imu>__FRAME_PREFIX___base_link</frame_id_imu>
      <topic_imu>__NS__/sensor/imu</topic_imu>            <!-- relativo -->
      <update_rate_imu>200</update_rate_imu>
      <remove_gravity_imu>false</remove_gravity_imu>
      <ros>
        <namespace>__NS__</namespace>
      </ros>
    </plugin>

    <!-- Bar贸metro -->
    <plugin name="barometer_plugin" filename="libbarometer_plugin.so">
      <link_name_baro>base_link</link_name_baro>
      <frame_id_baro>__FRAME_PREFIX___base_link</frame_id_baro>
      <topic_baro>__NS__/sensor/baro</topic_baro>     <!-- relativo -->
      <update_rate_baro>50</update_rate_baro>

      <ref_altitude_baro>0.0</ref_altitude_baro>
      <p0_baro>101325.0</p0_baro>
      <T_baro>288.15</T_baro>

      <ros>
        <namespace>__NS__</namespace>
      </ros>
    </plugin>

    <!-- Magnet贸metro -->
    <plugin name="magnetometer_plugin" filename="libmagnetometer_plugin.so">
      <link_name_mag>base_link</link_name_mag>
      <frame_id_mag>__FRAME_PREFIX___base_link</frame_id_mag>
      <topic_mag>__NS__/sensor/mag</topic_mag>          <!-- relativo -->
      <update_rate_mag>100</update_rate_mag>

      <Bx_world>2.0e-5</Bx_world>
      <By_world>0.0</By_world>
      <Bz_world>-4.0e-5</Bz_world>

      <ros>
        <namespace>__NS__</namespace>
      </ros>
    </plugin>

    <!-- Ground Truth -->
    <plugin name="ground_truth_plugin" filename="libground_truth_plugin.so">
      <link_name_gt>base_link</link_name_gt>
      <frame_id_gt>world</frame_id_gt>
      <topic_gt>__NS__/ground_truth/pose</topic_gt>    <!-- relativo -->
      <update_rate_gt>100</update_rate_gt>
      <param_ns>ground_truth</param_ns>
      <ros>
        <namespace>__NS__</namespace>
      </ros>
    </plugin>
  </gazebo>

</robot>
